In [3]:
import numpy as np

In [6]:
a = np.array([[1,2,3],[3,4,5],[5,71,2]])

In [7]:
b = np.array([[2,4,3],[9,8,6],[6,2,7]])

In [9]:
print("Addition of matrices is :\n",np.add(a,b))

Addition of matrices is :
 [[ 3  6  6]
 [12 12 11]
 [11 73  9]]


In [10]:
print("Subraction of matrices is :\n",np.subtract(a,b))

Subraction of matrices is :
 [[-1 -2  0]
 [-6 -4 -1]
 [-1 69 -5]]


In [11]:
print("Multiplication of matrices is : \n",np.multiply(a,b))

Multiplication of matrices is : 
 [[  2   8   9]
 [ 27  32  30]
 [ 30 142  14]]


In [12]:
print("Division of martrices is :\n",np.divide(a,b))

Division of martrices is :
 [[ 0.5         0.5         1.        ]
 [ 0.33333333  0.5         0.83333333]
 [ 0.83333333 35.5         0.28571429]]


In [16]:
print(np.char.add(['welcome','Hi'], [' to Javatpoint', ' read python'] ))

['welcome to Javatpoint' 'Hi read python']


In [17]:
print(np.char.add([' hello ','welcoming'],['friends','codemania']))

[' hello friends' 'welcomingcodemania']


In [20]:
np.random.randint(low=1,high=10,size=6)

array([3, 4, 2, 1, 9, 7])